### ISSUE TITLE
Question: which pin does IR send use?

### ISSUE THREAD

**Issue by justsubhash** [baltom/IRremote_Particle_Photon#1]
Sorry, kind of a simple question but I couldn't easily find an answer.

**Comment by justsubhash** [comment]
Looks like it's A5?

**Comment by baltom** [comment]
Have only used the receive part myself, so not really sure. But i suppose one of the pins mentioned as "TIMER_PWM_PIN" in IRremoteInt.h file

**Comment by justsubhash** [comment]
FWIW: Yeah it's definitely A5. I tested all of them until I found the one that was working. I still don't know how to swap the pins to another PWM pin since the implementation is pretty low level.
